export function HomilyContent() {
  return (
    <div className="homily-content">
      <h2>A Vida e Morte de Joseph</h2>
      <p className="subtitle-italic">Texto produzido a partir de uma homilia do Padre Kleverton Bezerra, consagrado à Comunidade Doce Mãe de Deus.</p>
      <h2>A Promessa e o Testemunho de Joseph</h2>
      <p className="drop-cap"><span className="first-letter">G</span>ostaria, nesta homilia (sem me estender demasiado), de cumprir uma promessa que fiz a Nosso Senhor: a de que em todas as missões de Carnaval eu daria o testemunho de Joseph. Espero não ser exaustivo. Desde que fiz essa promessa, Nosso Senhor aproveitou bem o compromisso: já estive em Guarabira, vim para cá e andei por muitos outros lugares, sempre dando esse testemunho da graça que o Senhor me permitiu viver ao acompanhar espiritualmente Joseph nos dois últimos meses antes de ele partir para o céu.</p>
      <p>Não estou canonizando Joseph aqui, mas tenho duas coisas a afirmar. Primeira: ele morreu em estado de graça. Isso eu posso dizer, afirmar e confirmar. Segunda: ele morreu em odor de santidade, porque quem chegava ao quarto dele nos sábados sentia um suave perfume que vinha do quinto andar. Essas duas realidades são verdade.</p>
      <p>Se ele será canonizado, se será beatificado, se algum dia terei a graça de celebrar uma missa em honra de São Joseph da Paraíba, eu não sei. Mas que ele está no céu: disso não tenho dúvida. Se ele não estiver no céu, serei eu o primeiro a não entrar! Agora vou explicar por que acredito nisso.</p>
      <p>Identifico três dimensões de santidade na vida de Joseph. Mas antes de falar sobre elas, deixem-me contar um pouco do histórico dele.</p>
      <h2>Histórico: De Nietzsche ao Altar</h2>
      <p>Joseph era ateu. Ateu convicto, niilista. Seu mestrado em Filosofia é sobre Nietzsche. Era completamente ateu, do tipo que tinha todos os argumentos contra você quando alguém falava de Deus ou da existência de Deus.</p>
      <p>Quando foi que começou a conversão de Joseph? Durante a pandemia. Com o início do *lockdown*, Joseph teve mais tempo para refletir, para filosofar, para buscar a verdade. E quem busca a verdade sempre encontra Jesus, porque Jesus é a verdade.</p>
      <p>Nesse período, em um dos seus momentos de introspecção, ele pediu a Deus que lhe mostrasse para onde devia ir. Então, quando soube que as missas na Paraíba iriam ser novamente permitidas publicamente, sentiu no coração que esse era o sinal de que devia ir à missa. Entendeu que Deus lhe dizia: &apos;Vá à missa.&apos; E foi.</p>
      <p>Na missa, encontrou o Padre João Paulo. Naquele mesmo dia fez uma confissão geral, colocou tudo diante de Deus, participou da Santa Missa. Pouco depois, contudo, as restrições voltaram e as missas foram suspensas novamente. Mas Joseph então entrou em contato com um jovem da Pascom chamado Renan, e passou a participar das missas de forma mais discreta. Foi assim que o amor a Nosso Senhor Jesus Cristo foi crescendo nele.</p>
      <p>Quando as coisas começaram a se normalizar, Joseph queria participar de tudo, porque tudo era uma primeira vez na sua vida. A primeira Semana Santa, a primeira adoração, a primeira festa de Nossa Senhora, e ele chorava em tudo, em cada momento. Mencionavam o nome de Nossa Senhora e ele ficava radiante, com os olhos cheios de lágrimas. Porque tudo era muito para ele; tudo era irrupção da graça, tudo era muito intenso.</p>
      <p>À medida que se engajou na Igreja, Joseph iniciou um trabalho apostólico próximo ao altar, na paróquia, principalmente na comunidade do Coração de Jesus. Dedicou-se ao serviço do altar, às leituras e, de modo especial, ao serviço dos pobres. Tinha uma pastoral de rua. O que era particularmente belo no trabalho de Joseph com os pobres é que ele não apenas dava comida: devolvia ao pobre a sua dignidade. Porque ele se dava ao pobre: olhava nos olhos, pegava na mão, abraçava, beijava, estava inteiramente presente. Dava uma atenção que era própria dele.</p>
      <h2>O Câncer e a Hospitalização</h2>
      <p>Tudo isso foi antes de o câncer chegar. Não muito depois desse processo de conversão, Joseph foi diagnosticado com câncer no estômago. Fez o tratamento e, em junho de 2022, recebeu a notícia de que estava curado. O câncer tinha desaparecido.</p>
      <p>Junho passou bem. Julho, agosto, setembro também. O aniversário de Joseph é em 5 de setembro. Mas entre os dias 10 e 15 desse mesmo mês, ele começou a sentir-se mal novamente: dores intensas na região abdominal, principalmente na parte do intestino, e crises de vômito. Comia alguma coisa e passava mal, sempre vômito, aquele ciclo todo. Num primeiro momento, tratou a situação como algo banal, uma infecção intestinal, talvez. Assim foi setembro.</p>
      <p>Em outubro, as coisas começaram a piorar significativamente. Ele já não conseguia comer. No dia 13 de outubro (data do milagre do sol, última aparição de Nossa Senhora de Fátima), Joseph chegou ao Hospital Universitário (HU) bastante debilitado. Já mal conseguia andar. Quando perguntaram o que estava sentindo, ele respondeu com simplicidade: &apos;Uma dorzinha.&apos; Fazia semanas que não se alimentava adequadamente, já sofria com a intensidade de dor própria de um câncer em fase terminal, e descrevia isso como &apos;uma dorzinha.&apos;</p>
      <p>Foi hospitalizado e encaminhado para o quinto andar do HU, no último quarto do lado direito. Quando chegou, o diagnóstico já era definitivo: metástase, câncer em fase terminal. Humanamente falando, não havia mais nada a fazer. Era tempo de preparação.</p>
      <h2>O Encontro no Hospital</h2>
      <p>No dia 7 de dezembro, eu conheci Joseph. Naquela tarde, após celebrar a Missa do meio-dia na Igreja Mãe do Amor Belo, fui abordado por uma jovem estudante chamada Hilary, que se aproximou com uma voz tímida e disse: &apos;Padre, o senhor poderia vir comigo? Há doentes que precisam receber a Unção dos Enfermos e fazer confissão.&apos; Eu disse que sim, ainda que relutante, já que era segunda-feira, o dia que eu reservava para arrumar meu quarto. Mas fui.</p>
      <p>Chegamos ao hospital, administrei os sacramentos, e quando eu estava concluindo, por volta das 21h30, Hilary disse: &apos;O senhor tem que conhecer o meu irmão.&apos; Pensei: mais uma coisa. Mas ela insistiu: &apos;Padre, o senhor precisa conhecer ele.&apos; Perguntei se havia algum sacramento para administrar. Ela disse que não. &apos;É porque o senhor tem que conhecer ele.&apos; Fui.</p>
      <p>Quando entrei no quarto, entendi imediatamente por que precisava ir. Joseph abriu aquele sorriso que era tão seu, os olhos a brilhar, e a primeira pergunta que me veio foi: &apos;Quem foi que disse que esse rapaz está doente?&apos; Ele me recebeu de modo tão fraterno, e houve de imediato uma proximidade tão grande, como se nos conhecêssemos há muito tempo.</p>
      <p>A primeira coisa que Joseph fez foi me apresentar uma cruz: &apos;Padre, preciso lhe apresentar minha companheira.&apos; Dormia com ela. Respondi: &apos;Então você está bem acompanhado.&apos; Em seguida, ele disse: &apos;Eu preciso me confessar.&apos; Naqueles dois minutos iniciais de conversa, já era claro que havia ali algo diferente. Saíram as demais pessoas do quarto e nós dois ficamos em um colóquio espiritual de quase quarenta minutos. Não foi apenas uma confissão: foi um mergulho em algo muito profundo do amor de Deus que me marcou profundamente.</p>
      <p>Quando encerramos, Hilary comentou com humor: &apos;Ele só fala com o senhor.&apos; Não tínhamos percebido o tempo passar. Ao sair do quarto, Nosso Senhor colocou no meu coração: &apos;Faz tempo que ele não vai à missa.&apos; Eu disse: &apos;Mas Jesus, ele já comunga todo dia...&apos; E o Senhor insistiu: &apos;Mas a missa é a missa.&apos;</p>
      <p>Desde 13 de outubro, Joseph não se alimentava mais por via normal. Não comia, não bebia água, não ingeria nada; tudo o que chegava à sua boca era expelido. Até mesmo o cheiro de comida provocava vômito. As crises eram muito intensas e as dores aumentavam a cada episódio. Fazíamos tudo para evitar que vomitasse, para que as dores não se intensificassem.</p>
      <h2>Primeira Dimensão: A Eucaristia</h2>
      <p>Aqui está o primeiro sinal da vida de Joseph que quero destacar: a dimensão eucarística. A única realidade material que ele conseguia absorver, desde o dia 13 de outubro, era a Eucaristia.</p>
      <p>Vocês podem perguntar: &apos;Mas não é o Corpo de Jesus? Então é diferente do pão?&apos; É o Corpo de Jesus, sim; mas, como a catequese básica nos ensina, na transubstanciação há mudança de substância sem mudança dos acidentes. A substância muda, mas os acidentes permanecem: continua sendo pão, continua sendo vinho. Ora, se Joseph biologicamente não conseguia absorver nem água, como era possível que engolisse o Corpo de Jesus e não o expelisse, como expelia a água? É milagre. Cientificamente, isso não tem explicação. Ele não podia engolir água, mas comungava o Corpo e o Sangue de Nosso Senhor Jesus Cristo sem que fosse vomitado, como acontecia com tudo o mais.</p>
      <p>Essa é a dimensão eucarística da vida de Joseph. E ele comungava todos os dias, por meio de um ministro extraordinário da Eucaristia.</p>
      <p>No dia 7 de dezembro, ao sair do quarto de Joseph, senti Nosso Senhor dizer-me: &apos;Por que ele não vai à missa?&apos; Ele já comungava diariamente, mas o Senhor insistiu: &apos;A missa é a missa.&apos; Falei com Hilary: &apos;Posso celebrar a missa no quarto dele?&apos; Ela disse: &apos;Pode, Padre, mas depende de como ele estiver.&apos; Pedi que não lhe dissesse nada. Combinei que, se ele estivesse bem no dia de Nossa Senhora de Guadalupe, eu viria celebrar lá.</p>
      <p>Nossa Senhora de Guadalupe caiu numa segunda-feira. Esperei até o início da tarde, confirmei que Joseph estava bem e fui ao HU. Quando abri a porta do quarto, ele olhou para mim e perguntou imediatamente: &apos;O senhor veio celebrar a missa?&apos; E quando confirmei, ele se abriu em choro: &apos;Padre, desde que entrei aqui, peço a missa todos os dias. Todos os dias peço a missa.&apos;</p>
      <p>Fiquei comovido. Ele podia pedir qualquer coisa: pedir para ser curado, pedir para não sentir mais dor, pedir para comer. Mas o que ele pedia, desde o primeiro dia, era a missa. Celebramos a missa naquele dia, e a partir daí tomei a resolução de ir todos os domingos e em todas as solenidades.</p>
      <p>Todos que visitavam Joseph ouviam sempre a mesma expressão: &apos;Muito grato.&apos; Era a palavra dele, repetida em todas as circunstâncias. Quando lhe dávamos medicação, quando rezávamos com ele, quando chegávamos ao quarto: &apos;Muito grato, muito grato, muito grato.&apos; Só havia uma outra frase que dizia com igual frequência: &apos;Deixa de coisa!&apos;, expressão que usava quando alguém lhe dizia algo gentil ou o elogiava. Era assim: &apos;Você faz a gente feliz!&apos; — &apos;Deixa de coisa, deixa de coisa.&apos; Havia inclusive um episódio em que ele beijou minha mão quando cheguei, e quando tentei retribuir o gesto, ele disse: &apos;Deixa de coisa!&apos;</p>
      <p>Tudo isso era fruto da dimensão eucarística: o amor a Jesus na Eucaristia, a recepção cotidiana de Jesus na Eucaristia, o milagre da Presença Real que permanecia nele como verdadeiro alimento.</p>
      <h2>Segunda Dimensão: A Oblação</h2>
      <p>A segunda dimensão é a oblativa. Joseph, alimentando-se da Eucaristia, tornou-se Eucaristia, tornou-se oblação.</p>
      <p>Em 25 de janeiro foi a última vez que conversamos pessoalmente. Naquele dia, os sofrimentos tinham aumentado consideravelmente. Fui celebrar a missa com ele na festa da Conversão de São Paulo Apóstolo, de quem ele era muito devoto. No quarto, as crises de vômito foram muitas e as dores estavam muito intensas, a ponto de nos questionarmos se ele teria condições de comungar naquele dia. Antes da missa, ele pediu que o pai saísse e ficamos os dois. Foi o momento de falarmos abertamente sobre a morte.</p>
      <p>Perguntei a ele: &apos;Fora a dor, o que você está sentindo?&apos; Ele respondeu: &apos;Padre, estou muito cansado. Muito cansado da dor e do sofrimento.&apos; Disse-lhe: &apos;Você sabe que Nosso Senhor não vai permitir que você sofra mais do que pode suportar.&apos; Ele respondeu: &apos;Eu sei. Sei que ele está comigo, sei que não estou só. Mas estou com muito medo do que ainda tenho que sofrer. Porque não tenho medo de morrer — não tenho medo. Sei que vou encontrá-lo, me preparo para isso, quero muito encontrá-lo. Mas o sofrimento...&apos;</p>
      <p>Falei-lhe então de Jesus no Getsêmani: que diante da cruz que ia abraçar, Jesus também soluçou, e também disse ao Pai: &apos;Se possível, afasta de mim este cálice. Contudo, não a minha vontade, mas a tua.&apos; Conversamos abertamente sobre a proximidade da morte.</p>
      <p>Naquele momento, as dores estavam muito intensas. Percebi que Joseph precisava de morfina. Perguntei-lhe: &apos;Você pediu a morfina?&apos; Ele me olhou sem responder. Repeti: &apos;Joseph, você pediu a morfina?&apos; Silêncio de novo. Na terceira vez, ele respondeu: &apos;Padre, o senhor não acha que vou desagradar a Jesus se pedir a morfina agora?&apos; Disse-lhe: &apos;Não vai, porque Ele não quer o seu sofrimento.&apos; Ele retrucou: &apos;Mas eu não quero diminuir em nada o que tenho para dar a Ele.&apos; Respondi: &apos;Você não vai diminuir nada.&apos; E como eu sabia que ele não ia pedir por conta própria, disse: &apos;Por obediência, você vai pedir. Estou mandando você pedir.&apos; E ele pediu.</p>
      <p>Quando a morfina começou a fazer efeito, celebramos a Santa Missa. Naquele dia, com medo de comungar e expelir, ele me pediu uma alternativa. Propus: &apos;Vamos buscar uma colher, benzê-la, e você comunga apenas uma gota do Preciosíssimo Sangue.&apos; Ele assentiu, e assim comungou naquele dia.</p>
      <p>A partir do dia 26, as dores se intensificaram. De quinta a domingo à tarde, Joseph viveu o que a equipe médica chamou de &apos;dor absoluta&apos; (expressão usada nos casos terminais de câncer). Em palavras simples: ele só sentia dor. Não havia mais nada nele além de dor. E não havia nenhuma medicação que a diminuísse. Ele já tinha tomado as últimas doses possíveis de morfina. Não havia mais nada.</p>
      <p>Joseph viveu esse sofrimento sempre com essa dimensão oblativa, pois sabia pelo que estava oferecendo. Não perdeu nenhum de seus sofrimentos, nenhum. Tudo ofertou, tudo entregou. Certa vez, perguntei-lhe se fazia o ato de oferta. Ele respondeu: &apos;Padre, faço — mas faço logo quando acordo de manhã. Porque quando a dor está muito forte, é tão intensa que não consigo pensar. Para não deixar passar despercebido, já oferto de manhã tudo o que vou sofrer durante o dia.&apos; Essa era a sua disposição: &apos;Eu vou sofrer muito, e oferto tudo.&apos;</p>
      <p>Era também bonito ver a reação de Joseph quando recebia notícias de intenções pelas quais rezava. Muitas intenções eram confiadas a ele, às vezes sem que as pessoas percebessem que estavam fazendo isso. E quando alguém chegava e dizia &apos;Fulano se reconciliou com a mulher&apos; ou &apos;Aconteceu tal coisa&apos;, via-se uma lágrima escorrer pelo rosto dele. Toda vez que alguém entrava no quarto, Joseph perguntava: &apos;Como você está? Como você está?&apos; Ele se descentralizava completamente. Nessa dimensão oblativa, não era mais ele que importava: era Jesus que se ofertava, e eram os que se aproximavam dele.</p>
      <p>Todos os que se aproximaram de Joseph nesses momentos se sentiram profundamente amados. Se perguntassem: &apos;O que você sente quando entra no quarto de Joseph?&apos; A resposta era: amor. Disse a ele uma vez: &apos;Eu entendo hoje por que precisava vir, por que precisava te conhecer. Todos os dias na Santa Missa elevo a patena com a hóstia, e aqui estou vendo e tocando que o seu leito é uma patena e você é uma hóstia. Você está unido a Jesus que se oferta.&apos;</p>
      <p>Uma das primeiras coisas que Joseph me disse foi: &apos;Padre, se é para sair daqui e ofender a Nosso Senhor, prefiro não sair daqui. Prefiro permanecer aqui.&apos; Isso é uma virtude altíssima: preferir morrer de câncer a sair do leito e ofender Jesus. É a esperança num grau elevado, é um martírio aceito conscientemente, porque se sabe qual é a realidade que espera.</p>
      <h2>Terceira Dimensão: A União a Jesus Cristo</h2>
      <p>Nos últimos dias, no domingo à tarde, a equipe médica decidiu sedá-lo devido à intensidade desumana das dores. Eu estava viajando, fora de João Pessoa. Quando me avisaram sobre a possibilidade da sedação, liguei rapidamente para ele. Joseph disse: &apos;Padre, estão querendo me sedar. O senhor não acha que isso vai acelerar minha morte?&apos; Disse-lhe que era preciso verificar as possibilidades, o nível do sedativo, todos os detalhes, e que precisávamos garantir que ele recebesse os últimos sacramentos antes, pois talvez não voltasse da sedação.</p>
      <p>Ele respondeu: &apos;Tá certo, Padre.&apos; Conversamos, agradecemos um ao outro pela vida do outro, e marcamos um encontro no céu, se Deus me der a graça de chegar, pois ele já está lá.</p>
      <p>Nesse último momento, as dores continuavam. O Padre João Paulo foi ao hospital e celebrou a última missa com Joseph. E foi então que aconteceu algo muito belo, que é a terceira dimensão: a união, uma união tão grande com Jesus que o tornou outro Cristo. Eucaristia, Oblação e União.</p>
      <p>Até aquele domingo, todas as missas celebradas com Joseph tinham sido dentro do quarto, de forma mais íntima: ele, o pai, a mãe, eu, Hilary e, quando muito, mais alguém. Mas naquele dia, havia muita gente, e para se ter ideia: no início da enfermidade havia lista de espera para visitar Joseph; as pessoas se inscreviam para visitá-lo, e foi ele mesmo quem decidiu restringir as visitas. Mas nesse domingo, o médico que cuidava de Joseph pediu que saíssem do quarto. E então, diante da grande cruz que existe no quinto andar do HU, a cama de Joseph foi colocada diante da cruz, e todas as pessoas que ali estavam se reuniram em torno do seu leito para aquela última missa.</p>
      <p>Por graça divina, no momento em que o Padre João Paulo começou a Santa Missa, as dores cessaram. Depois de quinta, sexta, sábado e domingo sofrendo dor absoluta, no instante em que a missa começou, todos que estavam ali perceberam: quem acompanhava Joseph sabia que quando as dores diminuíam, ele fechava os olhos e dava um suspiro leve. Todos perceberam esse sinal, e assim ele ficou até o final da missa.</p>
      <p>Antes da missa ele pediu para se confessar, pois fazia exame de consciência todos os dias. Confessou-se, participou da Santa Missa, e na ação de graças fez um ato de amor a Jesus. Começou a falar em voz alta o seu amor por Jesus Cristo. Dizia o quanto O amava, o quanto era grato por estar unido a Jesus na cruz, o quanto era maravilhoso e belo participar da cruz com Jesus. E disse: &apos;Eu te amo, Jesus, não somente pelo que me deste na vida, mas principalmente porque posso estar na cruz contigo. E estou na cruz contigo.&apos;</p>
      <p>Quando a missa terminou, as dores voltaram, e Joseph precisou retornar ao seu quarto, o último do lado direito no corredor do quinto andar. Para chegar lá, tinha que percorrer o corredor inteiro. E o que fez Joseph? Em dor absoluta, nos últimos dias de vida, ele foi parando diante de cada quarto, olhando para cada doente, perguntando como estavam: &apos;Como você está? Jesus está com você. Aguente firme, você vai ficar bem.&apos; Como Jesus consolando as mulheres de Jerusalém. Quando levamos um pisão no dedo, queremos mandar o mundo inteiro embora. Joseph, em dor absoluta, parando para consolar cada enfermo no caminho de volta ao quarto.</p>
      <p>Na segunda-feira, ele foi sedado. Mas a história não terminou aí. Houve uma imprecisão médica: a dose do sedativo foi insuficiente, e Joseph passou a segunda sedado, mas na madrugada de segunda para terça, por volta de 1 hora da manhã, a medicação acabou. Ele voltou da sedação como se acordasse de um pesadelo, com a mesma intensidade de dor dos últimos dias, tudo de uma vez só. O que havia sofrido em três dias, sofreu novamente em cinco horas.</p>
      <p>Foi tão intenso que a sua mãe, que não havia saído do quarto em nenhum momento, não aguentou permanecer dentro com ele. Ela me disse depois: &apos;Padre, eu não sei como ele não morreu naquela hora.&apos; E também me disse, depois, por que entendeu que ele não havia morrido naquele momento.</p>
      <p>Ele foi sedado novamente na segunda. Dessa vez, a sedação fez efeito. Na terça, passou o dia sedado. Da terça para quarta, às 1h40 da manhã, a respiração de Joseph começou a diminuir. Às 2h30 da manhã, na quarta-feira (a primeira do mês de fevereiro, dia consagrado a São José), Joseph voltou para Deus.</p>
      <h2>Comungar o Amor e Tornar-se Amor</h2>
      <p>Essas são as três dimensões da vida e da entrega de Joseph: dimensão eucarística, dimensão oblativa e dimensão de união a Jesus Cristo, ao ponto de tornar-se presença de amor para todos ao redor. Se Joseph será canonizado ou beatificado, não sei. Mas de uma coisa posso testemunhar: o estado de graça no qual foi para Deus e o fruto que deixou.</p>
      <p>Na Missa de Corpo Presente, em Pombal, onde ele foi sepultado, disse algo que continua verdadeiro: não podemos guardar Joseph só para nós. Quem o conheceu, quem o experimentou, quem esteve com ele, não pode guardar essa palavra. No dia em que ele morreu, fui ao hospital assim que terminei a missa no Bessa. Fiquei com a família, ajudei nos preparativos para o sepultamento. E encontrei o médico que havia cuidado de Joseph mais de perto. Nos abraçamos sem nos conhecer, mas quando nos encontramos no corredor, não havia como não se abraçar. Disse a ele: &apos;Obrigado por tudo que fez por Joseph.&apos; Ele respondeu: &apos;Não, sou eu que agradeço por tudo que Joseph fez em mim, na minha vida.&apos;</p>
      <p>Os enfermeiros e as enfermeiras, quando terminavam o plantão, iam para lá nas horas de folga para cuidar dele. Duas enfermeiras me deram testemunhos que nunca esquecerei. Uma disse: &apos;Padre, chegou uma hora em que achei que estava apaixonada por ele. Meu Deus, eu estava em casa pensando nele, rezando por ele, e quando chegava ao hospital, a primeira coisa que fazia era correr para ver como ele estava. Não conseguia ficar longe. Meu Deus, eu estou apaixonada por Jesus!&apos; E a outra confirmou: &apos;É mesmo, tinha essa graça.&apos;</p>
      <p>A segunda enfermeira disse: &apos;Quando entrei no quarto, quando o olhei, me senti indigna, indigna do amor que vi nos olhos dele. Ao mesmo tempo, me senti tão amada, sem nem o conhecer. Não entendia por quê, mas me senti tão amada que me via como Maria Madalena aos pés de Jesus. Saí do quarto e fui direto para a sala de descanso dos enfermeiros. Chorava copiosamente, sem saber ao certo por quê, mas porque me sentia amada.&apos;</p>
      <p>Você tem que comungar. Concluindo: na vida de Joseph, posso testemunhar alguém que se tornou amor. Porque todos os dias comungava do amor, comungava de Jesus, comungava da fonte viva do amor, e tornou-se amor.</p>
      <p>Uma das coisas que mais me fez chorar, quando recebi a notícia da sua morte e fui falar com Jesus, foi dizer: &apos;Por que foi tão rápido? Por que foi tão rápido?&apos; Conheci Joseph em dezembro e Nosso Senhor o levou em fevereiro. A mãe dele, Dona Antônia, me perguntou: &apos;Desde quando o senhor conhece meu filho?&apos; Respondi: &apos;Dona Antônia, eu o conheci no dia 7 de dezembro.&apos; &apos;Do ano passado?&apos; &apos;Do ano passado.&apos; Mas foi suficiente para experimentar a eternidade.</p>
      <p>E é com isso que concluo, com a lição da vida de Joseph: comungar o amor, acolher Jesus em nós, é nos tornarmos Jesus. Seja pela via do sofrimento, seja pela via da dor, seja pela via dos pobres: não sei qual é a via que o Senhor tem para cada um de nós. Mas não importa qual seja: tem que ser no amor, por amor, com amor. Porque é isso que recebemos e acolhemos, e é nisso que precisamos nos transformar para que verdadeiramente estejamos unidos a Ele.</p>
    </div>
  );
}